### PR TITLE
Release changes back to main

### PR DESCRIPTION
**Pull request by emilio**
**Before submitting your pull request**

- [x] I agree to license my code under the [MPL 2.0 license](https://www.mozilla.org/en-US/MPL/2.0/).
- [x] I rebased my work on top of the main branch.
- [x] I ran `npm test` and all tests passed.
- [x] I added test coverages if relevant.

# Description

These changes are in the release branch but not in main yet.

### CODE REVIEW

**Comment by emilio** [comment]
Ah, or r? @dannycolin I guess :)

**Comment by dannycolin** [comment]
By changes, you mean only bumping the locales to the latest one right?

**Review by dannycolin — APPROVED** [review]

**Comment by emilio** [comment]
https://github.com/mozilla/multi-account-containers/pull/2623 actually does a further version bump on top, which is what I submitted to QA

**Pull request merged**
