### PR TITLE
Open new tabs in same container as previous tab

### LINKED ISSUE #462: Option to open new Tabs in the same Container
I often CTRL+T to open a new Tab. Currently, these are opened in the Default Container. It would be nice to at least have a configurable option to open new Tabs in the Context of the Tab I'm currently working on.

I am a system admin, and I do need to use different personas, often even for the same sites. Also, when I am working with one persona, I often need multiple tabs for the same persona, so this would help me not needing to change the persona on every new tab.

As mentioned above, saving the URL to always open in the same Container does not work for me, as the same site needs to be used with multiple personas.

### PR DESCRIPTION
**Pull request by totokaka**
This PR adds functionality that will try to open new tabs in the same container as the previously active tab in that window, if the new tab doesn't already have a container, and the previously active tab did.

Some undocumented / implicity functionality in the webextension API is used:
 * `onCreated` is called for a new tab before `onActivated` for that tab is called
 * `onUpdated` will be called for all new tabs, also `about:newtab` and the like (sets the favicon)
 * The first `onUpdated` for a new tab, that is not an `about:`-tab, will set the URL

It is a little bit wonky, as the original new tab is created and displayed (although not loaded) before it can be closed and a new tab can be created. However, it is the best workaround I can find to add this functionality until [Bugzilla 1406371](https://bugzilla.mozilla.org/show_bug.cgi?id=1406371) is solved.

This would fix #462, #448 and #406 (I think)
Also relates to #943 and #544

### CODE REVIEW

**Comment by mandawan** [comment]
Thanks for the PR ! Hope it'll be reviewed merged, and deployed on store soon.

**Comment by beatgammit** [comment]
Also relates to #1000

**Comment by jonathanKingston** [comment]
Thanks for the PR!
However we will be moving forward with the platform bug instead:  [Bugzilla 1406371](https://bugzilla.mozilla.org/show_bug.cgi?id=1406371) this hopefully should land in Nightly this week.

**Comment by m4dc4p** [comment]
Been a year - the platform bug never landed AFAICT. Could this PR get revived? I would really like functionality similar to the "sticky containers" extension (which I would use if it wasn't so buggy).

**Pull request closed without merging**
