### PR TITLE
added right and left arrow shortcuts for container submenu tabs

### PR DESCRIPTION
**Pull request by dnahol**
Addresses Issues #1009 and #1153 

Added left and right arrow shortcuts for viewing containers in popup browser menu are working. Note that in order to use left arrow, TAB must be pressed to change the focus to the left panel arrow button.

All npm tests passed.

This replaces and completes blocked PR from @tie-rack
 Mar 18 2018
https://github.com/mozilla/multi-account-containers/pull/1153#pullrequestreview-291387739
@maxxcrawford 
> This looks great! Can you please add the left key to go back to the main menu when inside a submenu? Happy to take another look after that.

#OutreachyApplicant, first Mozilla containers bug fix

### CODE REVIEW

**Comment by groovecoder** [comment]
Hmm ... we need to fix this up before we merge. In this fork, the focus seems to get "stuck" in the container tabs list panel. Can we make sure the left panel arrow button can activate without having to press TAB first?

**Comment by dnahol** [comment]
> Hmm ... we need to fix this up before we merge. In this fork, the focus seems to get "stuck" in the container tabs list panel. Can we make sure the left panel arrow button can activate without having to press TAB first?

Hi @groovecoder, got it!

Added a commit that changes the focus to the highest level element in the popup panel after opening the tabs with the right arrow. This allows one to then use the left arrow to move to the previous panel.

**Comment by dnahol** [comment]
Hi @groovecoder  and @maxxcrawford, 

Happy Monday!

Just following up again. Made the requested changes. Hoping to get a review/approval on this. (Outreachy applicant)

**Comment by groovecoder** [comment]
This is close, but now after using the right arrow to go into the `showTabs` panel, I can't use the down arrow to go down thru the tab items.

Sorry the UX and focus here is so finicky. @maxxcrawford - do you have any ideas or pointers for this one?

**Comment by dnahol** [comment]
@groovecoder oh! I had no idea! I'll take a look right now!

**Comment by dnahol** [comment]
@groovecoder @maxxcrawford 
Changed focus when showPanel is called and added changes from 

PR:
#1560 Fixes Issue #1559 Make Container Info Panel Tabbable

to make it possible to use down arrow to tab through Container Info panel after pressing right arrow to show tabs.

Here is a screen recording (coming)

**Pull request merged**
