### PR TITLE
In content tab

### PR DESCRIPTION
**Pull request by jonathanKingston**
- [x] Messaging to get active container list
- [x] Correct icons
- [x] Messaging to create the container
- [x] Layout to copy https://github.com/mozilla/testpilot-containers/issues/433#issuecomment-305455327

This is a supserset of other UI fixes, I only care about your thoughts on this commit:

https://github.com/jonathanKingston/testpilot-containers/commit/8d763a645a7f07f3bcedf0f5734290f921503022

Essentially this gives an ugly in content context menu for Shift+Alt+Click a link to select in a container. This is less distance to travel than the sub context menu on right click and I think this will be much easier to use. (Not sure if Alt+Click is possible on mac, it's used by Ubuntu I might be able to drop the Shift for Mac if that is the case).

This is for: #518

### CODE REVIEW

**Comment by groovecoder** [comment]
Do we want to keep this PR and branch alive? Or is it Overcome By Events?

**Comment by jonathanKingston** [comment]
I was just going to make a follow up addon instead it's an in content shortcut for faster container opening however doesn't belong in us. Will fix up this week (I would like to keep it open as a reminder).

**Comment by groovecoder** [comment]
Weekly check-in - do we still need this PR open? Can we convert it into an issue?

**Comment by jonathanKingston** [comment]
This has moved to: https://github.com/jonathanKingston/alt-context-containers-menu the code can live on there, I neatened up the code etc ready for publishing.

**Pull request closed without merging**
