### PR TITLE
Refactor async arrow functions

### LINKED ISSUE #972: Refactor to async arrow functions
See https://github.com/mozilla/multi-account-containers/pull/921#issuecomment-341670787 for details.

### PR DESCRIPTION
**Pull request by Paarmita**
Refractor all async function to arrow functions 
Fixed #972

### CODE REVIEW

**Comment by Paarmita** [comment]
@groovecoder Please review the PR :)

**Comment by ShivangiKakkar** [comment]
@jonathanKingston @groovecoder cc @Paarmita 
I went through the above PR and the travis build shows the syntax errors for the changes in all the files except in `popup.js` and `content-script.js`
In the other files, I guess the arrow function syntax isn't supported because the async functions are defined inside an object which is itself initialized in ES5 syntax.
What is your take on this?

**Comment by groovecoder** [comment]
The intent of https://github.com/mozilla/multi-account-containers/issues/972 and https://github.com/mozilla/multi-account-containers/pull/921#issuecomment-341670787 (like @jonathanKingston [says](https://github.com/mozilla/multi-account-containers/pull/921#issuecomment-425271223)) is **NOT** to change all named methods and functions into defined async arrow functions.

Then intention is to find async functions that are only ever used once, and move them into inline async arrow functions.

E.g., `assignManager` has an `_onClickedHandler` method. But that logic is only used in one place - during `init()`. The only reason we made `_onClickedHandler` a method is because, when we wrote it, JS didn't support using `async`/`await` in inline `=>` functions.

Now that JS supports `async () => {}` functions, we could move the `_onClickedHandler` logic from its own named function into an inline `async (info, tab) => {` ... `}` function in `init`.

Does that make sense?

With all that said, we may just close this particular PR and instead clean up unnecessary defined `async` functions as we make changes.

**Comment by jonathanKingston** [comment]
I think this makes sense to close for now. Thanks for the submission.

**Pull request closed without merging**
