### PR TITLE
✨ MozillaVPN Integration ✨

### LINKED ISSUE #2113: UI gets confused and suggests deleting a container that doesn't exist
If you delete a container, when you navigate through the UI and use the back button (e.g. to create a new container but then back out) you see a prompt to delete a container that doesn't exist.

### Steps to reproduce
1. Click the toolbar button for the extension.
2. Click "Manage containers".
3. Add a new container called "Test".
4. You should be back at the "Manage containers" page.  Click on the new container "Test".
5. Click "Delete this container".
6. Click "OK" to confirm deleting the container.
7. Note that you are unexpectedly thrown back to the main page instead of returning to the "Manage containers" page where you were before, so click "Manage containers" again to get back.
8. Click "New container" to make another new container.
9. Change your mind and click the back arrow at the top left, to cancel new container creation and return to the "Manage containers" screen.
10. Click the back arrow a second time to get back to the main screen.
11. Observe that instead of landing at the main page as expected, you are prompted to confirm deleting a container that doesn't exist.

It appears the history gets confused and instead of returning you to the main container page, it returns you to the previous delete confirmation page instead.

### Notes
Version: 7.4.0

### PR DESCRIPTION
**Pull request by lesleyjanenorton**
This uses `browser.runtime.connectNative()` to establish a Port between the MAC extension and the MozillaVPN client. If a Port cannot successfully be established, the extension will function as it always has but with a slightly updated interface and a new 'Advanced Proxy Settings' panel which can be accessed from the container management panel.

If the Port **is** established, the MAC interface will be updated with a slew of MozillaVPN specific features that facilitate painless per-container proxy configuration. 

- Some content is not final but is on track to be delivered by EOD Friday (MozillaVPN onboarding panel strings, tooltip warning strings, maybe a few tweaks elsewhere).

**Testing with the MozillaVPN client:** Use this client build to test the MozillaVPN integration locally
https://github.com/mozilla-mobile/mozilla-vpn-client/runs/3853073442 

Also fixes #2113,  #1805  - which would have been greatly exacerbated by the addition of the new Advanced Proxy Settings and MozillaVPN servers panel. 

... 
Will follow up here with more granular details after coffee and 8+ hours of sleep 🌪

### CODE REVIEW

**Comment by WhyNotHugo** [comment]
There seems to be no way reject the "Exchange messages with programs other than Firefox". For those of us that don't use Mozilla's VPN service and don't to expose new vector, is there any way to circumvent this?

Or is my only choice to simply uninstall multi-account-containers?

**Comment by sitedyno** [comment]
Please make the permission optional.

**Comment by bingoxo** [comment]
can this work with other vpn providers ? i'm assuming the extension is using SOCKS proxies right ?

**Comment by patricklucas** [comment]
@lesleyjanenorton / @bakulf Could someone from Mozilla respond to @WhyNotHugo's comment?

**Comment by lesleyjanenorton** [comment]
@WhyNotHugo @patricklucas the permission will be optional in 8.0.4

**Comment by achernyakevich-sc** [comment]
#2226 created to handle related changes for permissions handling. Posted here to be informed.

**Pull request merged**
