### PR TITLE
Automatically focus confirm button on confirm page

### LINKED ISSUE #2214: Enter key no longer works on "Open this site in your assigned Container?" page
- Multi-Account Containers Version: 8.0.2
- Operating System + Version: Arch Linux
- Firefox Version: 94.0
- Other installed Add-ons + Version + Enabled/Disabled-Status: not relevant

### Actual behavior

When a website is configured to open in a particular container, but the decision has not been *remembered*, it shows the `Open this site in your assigned Container?` page.

When pressing the *enter* key, it doesn't validate the button `Open in <selected container> Container`

Actually the button is not focused:

### Expected behavior

When pressing the *enter* key, it should open the website in the selected container.

The button is expected to be focused:

### Steps to reproduce
1. Assign a website to container
2. Open a new tab and visit the website
3. On the `Open this site in your assigned Container?` page, press *enter*.

### Notes

This is a regression from the version 8.0.1, which is in fact the 7.x version:

> Version 8.0.1
> Released Nov 2, 2021 - 178.47 KB
> Works with firefox 67.0 and later
> Restoring previous version for some users who may have been accidentally updated prematurely 8.0.

The `autofocus` attribute of the `button` attribute has been removed in commit 05dc48eac2d12dc65dc2e062ad3d64d0fe77051a:
```diff
-        <button id="deny" class="button">Open in <dfn id="current-container-name">Current</dfn> Container</button>
-        <button id="confirm" class="button primary" autofocus>Open in <dfn class="container-name"></dfn> Container</button>
+        <button id="deny" class="button" data-message-id="openInContainer" data-message-arg="current-container-name"></button>
+        <button id="confirm" class="button primary" data-message-id="openInContainer" data-message-arg="container-name"></button>
```

I'm working on a PR.

### PR DESCRIPTION
**Pull request by Exagone313**
Fixes #2214

This is a regression introduced in commit:
05dc48eac2d12dc65dc2e062ad3d64d0fe77051a

The autofocus attribute was removed unexpectedly in a localization
change.

### CODE REVIEW

**Comment by Exagone313** [comment]
Additional information:

I had this error when loading the extension locally:
> Extension is invalid
> Loading locale file _locales/.github/messages.json: Error: Error while loading 'file:///home/exagone/Git/multi-account-containers/src/_locales/.github/messages.json' (NS_ERROR_FILE_NOT_FOUND)

Same with web-ext (without verbosity):
> o: installTemporaryAddon: Error: Error: Could not install add-on at '/home/exagone/Git/multi-account-containers/src': Error: Extension is invalid

Temporarily fixed it by adding a symlink from `.github` to `en`. I don't know if it's a bug related to my environment or not.

**Review by danielfilho — APPROVED** [review]
I forked the repo to reintroduce this feature and before opening a pull request, I found this. I do extensive use of this add-on and it's really getting into my head that this property was removed.

Thank you for the contribution 👍

**Comment by Exagone313** [comment]
I have held updating this addon on all my systems/profiles until this is merged and published. This disrupts my workflow too much.

**Comment by groovecoder** [comment]
Thanks! Running workflow to check and will merge and set up a release.

**Review by groovecoder — APPROVED** [review]
Spot-check and code looks good.

**Comment by danielfilho** [comment]
Thanks for merging it @groovecoder, this is really nice. And thank you for all the effort on this project.

Just to calm down my anxiety, do you know what's the next step for the release? I take a look at the releases and it happens with quite a few months  between them. Is there anything we can do to help on this?

**Pull request merged**
