### PR TITLE
Fix awkward wording in delete warning message

### LINKED ISSUE #1051: Awkward wording when deleting a container
The current wording suggests (to me at least) that _all_ of my container tabs will be closed. The behavior is "any open tab for the container to be deleted will be closed".

Suggestion (IANAET*): "If you remove this container now, this container's tabs will be closed"

screen shot 2017-12-19 at 11 47 50

* I Am Not An English Teacher

### PR DESCRIPTION
**Pull request by mingchia-andy-liu**
Hi,

Fix  #1051.

- Include the number of tabs that will be closed when container is deleted
  - Calculate the number of tabs from the length of hidden tabs & opened tabs array
- Insert the warning message to the `span` tag that was originally there

### CODE REVIEW

**Comment by mingchia-andy-liu** [comment]
Hi,

For the failing test, I am not quite sure what is causing the failure or how to debug it. It seems to passing and failing randomly on my local. It would sometimes pass with 2001/2002 ms. Here is a [screenshot](https://i.imgur.com/r3kZwT3.png).

The same behavior seems to happen on the current master head as well (99db19). Any help is appreciated to debug this test.

**Comment by stoically** [comment]
@mingchia-andy-liu Regarding the test: That's fixed with the latest test-code in #1190 and has nothing to do with your PR.

**Comment by ShivangiKakkar** [comment]
@mingchia-andy-liu Hey! Your changes seems to work fine. May be you can rebuild your PR in travis-ci and check the error logs?

**Comment by mingchia-andy-liu** [comment]
@ShivangiKakkar Hi, I merged from the current master to my branch. The previous issue is resolved. But now the test is failing from a npm package `ajv`. I tried on the master with a fresh clone, it also fails.

**Error message**
```
Error: Cannot find module 'ajv/lib/compile/equal'
```

**Environments**
```bash
➜  multi-account-containers (master) ✔ npm --version
6.4.1
➜  multi-account-containers (master) ✔ node --version
v10.7.0
➜  multi-account-containers (master) ✔ nvm --version
0.32.1
```

**Steps to reproduce**
```bash
➜  multi-account-containers (master) ✔ npm install
...
➜  multi-account-containers (master) ✔ npm test
fails here
```

&nbsp;

I did some research, it seems like our `addons-linter@1.3.2` depends on `ajv@6.5.3`. Not sure why but `npm` keeps install `6.6.0` version instead of the latest `6.6.2`, even on travis as well. They fixed the error in `6.6.1`. See [the commit history](https://github.com/epoberezkin/ajv/commits/master) and [the fix they did for `6.6.1`](https://github.com/epoberezkin/ajv/commit/bf0fc0301e2a61cea17fe1f7b57c100594b846fb). I have cleared my `npm cache` and try it on a another computer. 

Not sure how to proceed from here.

**Comment by groovecoder** [comment]
That's odd re: npm package resolutions ... but I'm no longer surprised by `npm` weirdness.

I rebased on master and added a commit with `ajv` dependency uplifted straight into our own `devDependencies` which fixes the issue for Travis. I submitted https://github.com/mozilla/multi-account-containers/pull/1323 to supersede this PR.

**Comment by groovecoder** [comment]
Thanks @mingchia-andy-liu for the contribution!

**Comment by mingchia-andy-liu** [comment]
Thanks for amending my PR, wasn't sure if adding a dependency was a right approach.

**Pull request closed without merging**
