### PR TITLE
Wildcard subdomains - e.g. *.google.com

### PR DESCRIPTION
**Pull request by mckenfra**
#473 Assign all subdomains of a domain to a container.

E.g. after adding `www.google.com` to a container, go to the edit container screen and click on the `www` part of the domain name to change it to `___.google.com`. Then, any subsequent requests to subdomains such as `mail.google.com`, `calendar.google.com` or `drive.google.com` will all automatically open in the same container.

Unit tests included.

Subdomains

### CODE REVIEW

**Comment by groovecoder** [comment]
Thank you for your previous contributions to Multi-Account Containers. We're closing PRs with conflicts to prepare this repo for some work in the near future. If you would like to re-submit the changes in a branch from the latest `master` code, we would love to take another look at this!

**Comment by dustymabe** [comment]
@mckenfra - do you want to open a PR against latest `master` ?

**Comment by mckenfra** [comment]
> @mckenfra - do you want to open a PR against latest `master` ?

@dustymabe @groovecoder Yup sure, happy to do a new PR. Will it cause issues if I merge the latest master changes into my branch, and then resubmit the PR once I've fixed any merge conflicts?

I see in your "Contributing" readme doc, it says 

> Please do not include merge commits in pull requests; include only commits with the new relevant code.

**Comment by dustymabe** [comment]
@mckenfra - I'm not actually a mozilla dev, just a user interested in the feature :)





> Please do not include merge commits in pull requests; include only commits with the new relevant code.

I think what this means is that you should try to rebase on top of latest master code (i.e. you'll just have 1 commit on top of master). You might be able to do this with a `git pull --rebase` or just starting from a fresh checkout of master and then `cherry-pick`ing your commit for this PR from another branch. Sounds like there will be conflicts you'll need to fixup during the process.

**Comment by mckenfra** [comment]
@dustymabe Yes, I'm not a mozilla dev either, I just got involved with this plugin after stumbling on it by chance and liking it a lot! I've currently installed my own build of this plugin incorporating my pull requests (wildcard subdomains, container locking) in my day-to-day Firefox and it's working great. The only thing it's now missing is the ability to save/restore the assignments configuration, so that you don't have to start again from scratch whenever you reinstall the plugin. I can't see a super easy way to implement that, though...

Thanks for the tip about the `git pull --rebase`, very helpful, it led me to this: https://stackoverflow.com/questions/36148602/git-pull-vs-git-rebase and I found that `git fetch` and `git rebase origin/master` were the commands I needed.

**Pull request closed without merging**
