### PR TITLE
Adding assignment feature tests

### PR DESCRIPTION
**Pull request by stoically**
Hi,

since jkt signaled on IRC that adding some tests to the codebase is OK, here's a proposal that loads `popup.html` and `background/index.html` with `jsdom` and executes a basic assignment feature test:
* [Initialize browser with example.com tab in firefox-container-1](https://github.com/stoically/multi-account-containers/blob/9bc9509316d4032dbb701b312c7546ab8589dac2/test/features/assignment.test.js#L2-L10)
* [Click the `container-page-assigned` checkbox to assign example.com to firefox-container-1](https://github.com/stoically/multi-account-containers/blob/9bc9509316d4032dbb701b312c7546ab8589dac2/test/features/assignment.test.js#L12-L16)
* [Open new example.com tab in firefox-default container](https://github.com/stoically/multi-account-containers/blob/9bc9509316d4032dbb701b312c7546ab8589dac2/test/features/assignment.test.js#L18-L29)
* [Should create new tab with confirm page url](https://github.com/stoically/multi-account-containers/blob/9bc9509316d4032dbb701b312c7546ab8589dac2/test/features/assignment.test.js#L31-L41)
* [Should remove the new example.com tab in firefox-default container](https://github.com/stoically/multi-account-containers/blob/9bc9509316d4032dbb701b312c7546ab8589dac2/test/features/assignment.test.js#L43-L45)
* [Click the checkbox again to remove assignment of example.com](https://github.com/stoically/multi-account-containers/blob/9bc9509316d4032dbb701b312c7546ab8589dac2/test/features/assignment.test.js#L48-L52)
* [Open new example.com tab in firefox-default container](https://github.com/stoically/multi-account-containers/blob/9bc9509316d4032dbb701b312c7546ab8589dac2/test/features/assignment.test.js#L54-L65)
* [Should not create a new tab](https://github.com/stoically/multi-account-containers/blob/9bc9509316d4032dbb701b312c7546ab8589dac2/test/features/assignment.test.js#L67-L70)

If you find this useful I could add more feature tests based on this. Of course I'm open to feedback and willing to change stuff - just let me know what you think.

Libs used: jsdom, mocha, sinon, chai

Bumped travis nodejs version to `lts/*` (latest LTS Node.js release) to have ES6 support in the tests

Best regards

### CODE REVIEW

**Comment by groovecoder** [comment]
Whoa, this is a cool PR. @jonathanKingston - do you have time to check this out this week?

**Comment by stoically** [comment]
Glad you like it. Refactored a bit and wired `popup.browser.runtime.sendMessage` with `background.browser.runtime.onMessage`. That way the click in the popup automatically triggers the background which makes it imho a more reliable feature test.

**Comment by stoically** [comment]
Finished the refactorings that I initially mentioned

- [x] Rephrase and refactor the feature test to be less technical and more black-box-ish
- [x] Don't check for `browser.runtime.sendMessage` and `browser.storage.local.set` but instead yield onBeforeRequest and check if MAC reopens the tab correctly
- [x] Move "popup clicking" and "opening of tabs" behind helper functions - would make writing future feature tests easier

**Comment by stoically** [comment]
Tests currently fail because I've added one for #1114 - so if that should get merged, the tests would go green again.

**Pull request merged**
