### PR TITLE
Fixes #1670 Manually add URL's to a container

### LINKED ISSUE #1670: Manually add URL's to a container
- Multi-Account Containers Version: 6.2.3
- Operating System + Version: Kubuntu 19.10
- Firefox Version: Nightly `Mozilla/5.0 (X11; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0 ID:20200229214828`
<details>
<summary>Other installed Add-ons + Version + Enabled/Disabled-Status (Click to expand/hide)</summary>

About Sync 0.0.51
Amazon.com 1.1
Authenticator 6.0.1
Awesome RSS 1.3.5
Bing 1.1
CanvasBlocker 1.1 [DISABLED]
Certainly Something (Certificate Viewer) 1.2.3
Compat Report 0.1.0
Containers theme 1.0.3 [DISABLED]
Context Plus 0.6.0
Debian queries 2.3
Decentraleyes 2.0.13
Disconnect 5.19.3 [DISABLED]
DuckDuckGo 1.0
DuckDuckGo Privacy Essentials 2019.12.12 [DISABLED]
Emoji Cheatsheet for GitHub, Basecamp etc. 2.0.1
Enhancer for YouTube™ 2.0.99
Enterprise Policy Generator 5.1.0 [DISABLED]
Feedbro 4.0.3
Firefox DevTools ADB Extension 0.0.5
Firefox Lightbeam 2.1.0
Firefox Multi-Account Containers 6.2.3
FoxyProxy Standard 7.4.3
Google 1.0
Greasemonkey 4.9
HTTP/2 Indicator 3.0
IPFS Companion 2.10.0
Laboratory 3.0.7 [DISABLED]
MathML Font Settings 0.3.2
Native MathML 1.9.4
Nightly Tester Tools 4.0
Notes by Firefox 4.3.5 [DISABLED]
Offline QR Code Generator 1.6
PassFF 1.9.1 [DISABLED]
Plasma Integration 1.7
ProtonDB for Steam 1.6.0
React Developer Tools 4.4.0 [DISABLED]
Session Sync 3.1.12
Snooze Tabs 1.1.1
Tab Session Manager 5.2.0 [DISABLED]
To Google Translate 4.0.6
Tree Style Tab 3.3.6
True Sight 1.7.1
Twitter 1.0
Vue.js devtools 5.3.3
Wikipedia (en) 1.0
YouTube Container 1.3.0
eBay 1.0
uMatrix 1.4.0

</details>

### Actual behavior
No way to add redirecting URL's.
- **If you DON'T FORGET TO DO THIS EVERY TIME:**
  - Only way at moment is to use right-click and choose a container.
  - Else you are screwed...

### Expected behavior
To automatically open known redirect URI's we need a EASY way to add them to a container.
Sometimes you want to catch redirect links, to force them to always open in a certain container **before** the browser navigates to the destination of the link.
For this purpose we **NEED** a way to manually add URL's to a container of choice !

### Steps to reproduce
1. Try to add a rule using the UI for links like `https://go.microsoft.com/fwlink/?LinkID=xxxxx&wt.mc_id=fuckmedead`
2. Stuck because there is no way.
3. Write bug report on github, like i do now :wink: 

### Notes
Related issues: #719, #837, #839, #1057, #1075, #1180, #1335, #1317 and maybe many more im tired search now...

### PR DESCRIPTION
**Pull request by sherry13131**
Fixes the issues #1670 Manually add URL's to a container

**Implemented**:
- Added an input field in the "edit container" menu of each container
- Added URL will show immediately once added
- If the input URL already register to another container, the URL will add to the current one and remove from the previously registered container

**Demonstration**:
ezgif com-optimize

### CODE REVIEW

**Comment by ChrisLane** [comment]
Hoping this can be merged. It's currently very hard to select "Always open in..." for URLs that redirect.

**Comment by ikipatang** [comment]
Make it happen ! Please !

**Comment by TriMoon** [comment]
@maxxcrawford @sherry13131 
Why is this being held back so long?
Please fix the conflicts and merge, this is a MUCH needed feature...

**Comment by CanRau** [comment]
Yeeesss please 😍

And it'll fix #1227, too 🙏🎉

**Comment by ToS0** [comment]
Meanwhile is there a way to enter sites manually in a file or database?

**Comment by CanRau** [comment]
@toso here is a config file mentioned https://github.com/mozilla/multi-account-containers/issues/1227#issuecomment-403419706

And maybe this can help even though it looks a little outdated https://excellenttips.wordpress.com/2018/07/05/editing-mozilla-firefox-container-urls/

**Comment by ToS0** [comment]
Thx @CanRau, I suppose the handling has changed since the Wordpress page was written in 2018, since this particular folder doesn't contain any data of the Multi-Account Plugin.
However, I could see that there are a lot of folders and files are created for each container in .../profile/storage/default/ - in addition to the files for other extensions. There are mainly sqlite databases, I can open with the DB Browser and see my data, but since there are probably cross-reference and alike, I don't want to mess with the data directly.
So it seems there is easy way to config -- we need an API at least, better an UI...

**Comment by Meshikhah** [comment]
Please someone merge this request. It will be really useful.

**Comment by rhclayto** [comment]
This should happen. The code needs to be refactored because MAC has changed a little in the meantime. For example, methods like `setOrRemoveAssignment` & `addEnterHandler` are now on the `Utils` object, not the `Logic` object. The CSS styling needs to be fixed. And the list of sites assigned to a container is now on a sub-page of the pop-up, not on the contaner's page, as shown in the OP's video.

**Comment by grahamperrin** [comment]
#839

**Comment by kurahaupo** [comment]
Hi @sherry13131, just to let you know that I've rebased your code and resubmitted it as PR #2114.

I've made some minor changes to cope with merge conflicts, and fixed one bug, but otherwise it's all your work, thankyou.

**Comment by dannycolin** [comment]
Closing in favor of #2114

**Pull request closed without merging**
