### PR TITLE
Set up CI with Azure Pipelines

### PR DESCRIPTION
**Pull request by dscho**
This gives us not only testing on Linux, but also on Windows.

If need be, we can even add macOS testing!

### CODE REVIEW

**Comment by dscho** [comment]
Looks like Travis encounters the very same timeout discussed in https://github.com/mozilla/multi-account-containers/pull/1349.

Absent a better method, I will close and re-open the PR to force a rebuild.

**Comment by dscho** [comment]
Okay, that "fixed" it. @groovecoder could you have a look at this PR? In order to make use of the Azure Pipeline, you will have to install the Azure Pipelines GitHub app (just direct the browser to https://github.com/marketplace/azure-pipelines, you will need to set up a "plan", but it really is free). The easiest would actually be to merge the PR first (no big harm in that, I tested it, and it only adds a file anyway), then set up the app, as it will auto-detect the `.yml` file and set things up almost automatically.

**Comment by groovecoder** [comment]
Thanks for the PR. While I'd like to have Windows coverage, we're keeping a pretty small list of GitHub applications that are authorized on mozilla repos. I'll check around to see if we can add Azure Pipelines to this repo, but I can't promise we'll be able to activate it on this repo.

Is there any chance you could set this up on a fork of your own that automatically mirrors ours?

**Comment by dscho** [comment]
> Is there any chance you could set this up on a fork of your own that automatically mirrors ours?

Sure, but that would lose most of the benefits: PR builds would not happen.

**Comment by kendallcorner** [comment]
Thanks for this contribution. However, we don’t plan to merge this, and now that we’ve launched the [Sync](https://blog.mozilla.org/security/2020/02/06/multi-account-containers-sync/) functionality, we’re closing some open PRs to make room for a couple more bug-fixes and updates.

**Comment by dscho** [comment]
Well, this is disappointing, but of course it's your right to do that.

**Pull request closed without merging**
