### PR TITLE
Allow Webextensions to get,set and remove  assignments

### PR DESCRIPTION
**Pull request by ramkumar-kr**
Hi,

I'm  the author of the [containers-sync](https://addons.mozilla.org/en-US/firefox/addon/containers-sync/) extension and I have been getting requests to sync assignments along with containers.

Taking inspiration from #1095 , I added a few more enhancements which would enable extensions with "contextualIdentities" permission to get all assignments for a container, set and remove assignments.

### CODE REVIEW

**Comment by frankhommers** [comment]
I would love this functionality!

**Comment by maxnordlund** [comment]
This would also help clean up `storage.js` that is filled with [temporary containers](https://github.com/stoically/temporary-containers) (5302 empty ones last I checked).

Of course that's kinda my own fault, but still, having an API like this would allow extensions like temporary containers to clean up after themselves.

**Comment by groovecoder** [comment]
Haven't had a chance to look into this specific PR, but [this comment](https://github.com/mozilla/multi-account-containers/issues/1415#issuecomment-509728750) on another issue to synchronize containers made me realize that integrating code from your [containers-sync](https://addons.mozilla.org/en-US/firefox/addon/containers-sync/) extension may be relatively straight-forward project for this extension.

I'm going to spend a few cycles seeing if I can draw up a project statement-of-work for that to get some help on it.

**Comment by stoically** [comment]
@groovecoder I'd be interested in helping out implementing export/import/sync for MAC. Did you already have a chance working on that statement-of-work? `containers-sync` seems to operate solely on container names - which might be prone to unexpected behavior if containers are renamed. Maybe a solution to that would be to generate UUIDv4's for the containers, so they can get uniquely identified.

In general I would support merging and publishing this PR, so @ramkumar-kr and others can experiment and see how things work out. Although I'm a bit biased, because being able to set assignments through the API would allow me to implement an [often requested feature](https://github.com/stoically/temporary-containers/issues/170) in [Temporary Containers](https://github.com/stoically/temporary-containers/).

**Comment by groovecoder** [comment]
This was a great contribution, and led directly to [@kendallcorner building sync into Multi-Account Containers](https://blog.mozilla.org/security/2020/02/06/multi-account-containers-sync/).

But, an API for site assignment data opens a hole that could leak someone's browsing history/sites to other add-ons in unexpected and hard-to-inform ways.

Closing this unless or until we come up with a way to enforce user consent before allowing this access.

**Pull request closed without merging**
