### PR TITLE
identities list in container panel is now tabbable and buttons are ac…

### PR DESCRIPTION
**Pull request by dnahol**
…cessible via enter key

#1547 
Before Fix: 
Here is a GIF screen recording before the added functionality. 
Notice we cannot tab through to the right Show Tabs arrows or press enter to show the corresponding Container Info panel.
PanelTabbable

After Fix:
Here is a GIF screen recording showing the added functionality. 
Notice we can now tab through to right Show Tabs arrows and press enter to show the corresponding Container Info panel.
PanelTabbableFixed

### CODE REVIEW

**Comment by dnahol** [comment]
@groovecoder @maxxcrawford What do you think?

**Comment by groovecoder** [comment]
Did https://github.com/mozilla/multi-account-containers/pull/1524 take care of this one too?

**Comment by dnahol** [comment]
Hey @groovecoder- no, actually this one allows you to navigate via Tab and Enter, without having to use the arrow keys at all. 

As you can see in the "After" screen recording above, after this PR, you can Tab directly tab into the Show Tabs right arrow button and press Enter.

You will notice that in #1524 you can't tab into the Show Tabs arrows directly, which means you must use the arrow key to get to Show Tabs. You can see that in the "Before" screen recording above.

**Comment by groovecoder** [comment]
Ah, this is a good fix ... but I'm afraid it might disrupt user habits.

In the current version, (on Mac) you can:

1. `<ctrl>`+`.` to open the panel, and then:
  * `1` to open a new tab in the 1st container
  * `2` to open a new tab in the 2nd container
  * etc.

mac-keyboard-panel-before

On this branch, when a tab is open for a container in the list, the arrow element seems to get the click events for `2`, `4`, `6`, etc. ?

mac-keyboard-panel-after

**Comment by dnahol** [comment]
Hi Luke,

Thank you for the detailed feedback and screencasts! I’m still having
trouble understanding this screen recording and comment, thank you in
advance for bearing with my questions:

1.
In your screen recording is the focus stuck and unresponsive to the arrow
keys and tab keys?
2.
Can you clarify what you mean by “ the arrow element seems to get the click
events for 2, 4, 6, etc. ?”

Will check this thread the branch when I get home to my laptop soon!

**Comment by dnahol** [comment]
1. The issue where the focus seems to be stuck is fixed via merging upstream commits from the #1524 merge. 022d119 "merging upstream" commit above.

2. The issue where the container tab open shortcuts are triggering the wrong events is fixed via commit 5d0ba8e "fixed keyboard shortcuts" above. This amends commit #992 "Adds shortcuts to open containers" while maintaining the same functionality discussed there.

Screen recording shows functioning keyboard shortcuts 2, 4, 6, 8, and 0. 

ContainerShortcutsFixed PR

**Comment by maxxcrawford** [comment]
Closing this PR as it applies to pre-7.0 [UI flow](https://github.com/mozilla/multi-account-containers/releases/tag/7.0.0).

**Pull request closed without merging**
